version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/bookstore/server
permissions:
  - object: /var/www/html/bookstore/server
    pattern: '**'
    owner: ubuntu
    group: ubuntu
hooks:
  # ApplicationStop:
  # DownloadBundle:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ubuntu
# ValidateService:
